Genomes updated

diff --git a/NX.Engine/Hive/Genomes/certbot/Dockerfile b/NX.Engine/Hive/Genomes/certbot/Dockerfile
--- a/NX.Engine/Hive/Genomes/certbot/Dockerfile
+++ b/NX.Engine/Hive/Genomes/certbot/Dockerfile
@@ -1,21 +1,17 @@
-# FROM https://github.com/joshkunz/certbot-docker
-
-FROM alpine:3.12
+FROM {repo_project}/base:{tier}
 LABEL {proj_label}
 
-RUN apk --no-cache update && \
-    apk --no-cache upgrade && \
-    apk --no-cache add \
-        certbot \
-        fish \
-        jq \
-        openssl \
-        tini
+RUN set -xe \
+  && apt-get update \
+  && apt-get install -y cron tini certbot jq \
+  && update-rc.d cron disable \
+  # cleanup
+  && apt-get autoremove \
+  && apt-get clean \
+  && rm -rf /var/lib/apt/lists/*
 
-COPY crontab /crontabs/root
-COPY renew-all /run/
-COPY start.fish /run/
+COPY ./run /run
 
 VOLUME /certs
 
-ENTRYPOINT ["tini", "--", "/run/start.fish"]
+ENTRYPOINT ["tini", "--", "bash", "/run/start"]
